import type { Metadata } from "next";
import { Prata } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const prata = Prata({
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "Atelier Studio | Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${prata.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
